name: Personal Wiki Setup
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

defaults:
  -
    scope:
      path: ""
    values:
      twitter_username: "nahbek"
      ga_id: "G-9D0H2T76M6"
    scope:
      path: "wiki/" # an empty string here means all files in the project
    values:
      importance: 5
      layout: post
      
