title: Nahuel Yazbek
url: https://nyazbek.github.io
description: Essays and notes by Nahuel Yazbek.
author: Nahuel Yazbek
email: nahuelayazbek@gmail.com
twitter_username: nahbek
ga_id: G-9D0H2T76M6

permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - minify_css.sh
  - suffix_stats.sh

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
